### ISSUE TITLE
Intel i9-13900HX is not supported. 

### ISSUE THREAD

**Issue by evertvorster** [powercap/raplcap#14]
Hi there!

It was a long and torturous road that led me here. 
My i9-13900HX CPU in a Sager laptop is getting heavily throttled in Linux. 

This utility is telling me my CPU is not supported:
```
[evert@Evert ~]$ sudo rapl-configure-powercap 
[ERROR] [raplcap-powercap] powercap_intel_rapl_get_time_window_us: No data available
Failed to get peak power limit: No data available
```

And:
```
[evert@Evert ~]$ sudo rapl-configure-msr 
[ERROR] [raplcap-msr] CPU not supported: Family=6, Model=B7
Failed to initialize: Operation not supported
```

Rapl-info is providing some useful info:
```
[evert@Evert ~]$ rapl-info 
Zone 0
  name: package-0
  enabled: 1
  max_energy_range_uj: 262143328850
  Constraint 0
    name: long_term
    power_limit_uw: 135000000
    time_window_us: 95944704
    max_power_uw: 55000000
  Constraint 1
    name: short_term
    power_limit_uw: 162000000
    time_window_us: 2440
    max_power_uw: 0
  Constraint 2
    name: peak_power
    power_limit_uw: 315000000
    max_power_uw: 0
  Subzone 0
    name: core
    enabled: 0
    max_energy_range_uj: 262143328850
    Constraint 0
      name: long_term
      power_limit_uw: 0
      time_window_us: 976
  Subzone 1
    name: uncore
    enabled: 0
    max_energy_range_uj: 262143328850
    Constraint 0
      name: long_term
      power_limit_uw: 0
      time_window_us: 976
Zone 1
  name: psys
  enabled: 1
  max_energy_range_uj: 262143328850
  Constraint 0
    name: long_term
    power_limit_uw: 280000000
    time_window_us: 95944704
  Constraint 1
    name: short_term
    power_limit_uw: 300000000
    time_window_us: 976
```

**Comment by connorimes** [comment]
Hi Evert, thanks for the detailed report.

There does indeed appear to be a bug in the powercap backend - it shouldn't be looking for a time window for the peak power constraint.

However, your CPU _should_ be supported in the msr backend with latest stable RAPLCap release (v0.9.0).  Since I don't have this particular CPU model, I can't test it myself.  Can you please share what package version or git revision you're using, and verify that you've re-compiled if you updated?

**Comment by evertvorster** [comment]
Hi there!

Thanks for the quick reply!
I was unaware of the existence of both powercap and RAPLcap until yesterday, and so did not have them installed on my Arch system. 

The sources to both powercap and RAPLcap were downloaded yesterday, and compiled on this Arch system which was also updated yesterday, incidentally. 

powercap is at version 0.6.0, and the third time it's packaged. 
raplcap is at version 0.9.0, and also the third time this source is packaged. 

At the moment there does not exist a git version of either package, but I can make those quite easily, if required.

**Comment by evertvorster** [comment]
Probably unrelated to this bug report, but you might be the right person to ask:
Where are the initial values for the powercaps set?
Who determines what they are? How does this all work? 
Can you point me to some documentation on the subject so I can educate myself?

**Comment by evertvorster** [comment]
One more data point. 
I use intel p_states as the CPU frequency controller on this system, rather than cpufreq. 

Does that make any difference to this application?

**Comment by connorimes** [comment]
I didn't even know `powercap` and `raplcap` sources were packaged for Arch.  I wish someone had talked to me first, I would've asked them to not include `rapl-info` and `rapl-set` with `powercap` - those binaries are deprecated, folks should be using the more general `powercap-info` and `powercap-set` binaries instead... oh well.

I now also see the bug in the RAPLCap msr backend - the core support was there but it wasn't included when checking cpuid.

I've pushed changes to the master branch that should fix these problems.  Would you mind cloning this repository and testing the changes?  The README includes instructions for building - they are simple.  I don't know exactly how Arch packages things, but it looks like it might include the development headers automatically, so when building RAPLCap, it should detect the `powercap` backend dependency automatically.  You should see it build both `libraplcap-msr.so` and `libraplcap-powercap.so`.  Relative to your build directory, the rapl-configure binaries will be at `./msr/rapl-configure-msr` and `./powercap/rapl-configure-powercap`.  You *don't* need to run "make install".

**Comment by connorimes** [comment]
To answer your other questions...

I believe Intel specifies the initial RAPL power limits and time windows.  Your computer manufacturer might be able to change these, and probably does at least for the Platform (aka PSys) zone, since that considers the larger system, not just the CPU.  However, there isn't usually documentation at this level of detail.  Intel's product spec pages usually specify some power values, but they don't always map directly to RAPL settings, e.g., see [1] for your CPU.  When they do match, it's usually a "thermal design power" value that matches with the package zone's long term power constraint, but I don't see that for [1].

I'm not exactly sure what you mean when you say you "use intel p_states [...] rather than cpufreq".  AFAICT, the `intel_pstate` kernel module is a wrapper around more traditional `cpufreq` scaling drivers though.  Just from an initial glance, I'd guess it's imposing some additional constraints on which frequencies RAPL is allowed to use.  RAPL functions by changing frequencies in response to CPU demand while enforcing both short- and long-term power limits (notionally to prevent overheating).  This is in contrast to older approaches which require software (via the kernel) to specify the frequency to use, which is less efficient both in terms of performance and power.

[1] https://ark.intel.com/content/www/us/en/ark/products/232171/intel-core-i9-13900hx-processor-36m-cache-up-to-5-40-ghz.html

**Comment by evertvorster** [comment]
Thanks for the timely fix. 
There now exists a raplcap-git package in AUR, and when you install it you get the latest git master installed into your system.

Here is the output on my system:
```
[evert@Evert raplcap-git]$ sudo rapl-configure-msr
      enabled: true
      clamped: false
       locked: false
   watts_long: 135.000000000000
 seconds_long: 96.000000000000
  watts_short: 162.000000000000
seconds_short: 0.002441406250
  locked_peak: false
   watts_peak: 315.000000000000
       joules: 23251.590698242188
   joules_max: 262144.000000000000
[evert@Evert raplcap-git]$ sudo rapl-configure-powercap
      enabled: true
   watts_long: 135.000000000000
 seconds_long: 95.944704000000
  watts_short: 162.000000000000
seconds_short: 0.002440000000
   watts_peak: 315.000000000000
       joules: 23480.298593000000
   joules_max: 262143.328849999991
[evert@Evert raplcap-git]$ 
```

Since my system operates inside these parameters anyways it's still not the solution of why my CPU is getting throttled. 
You can read about my trials and tribulations here:
https://bugzilla.kernel.org/show_bug.cgi?id=217976

The intel p_states driver conflicts with and replaces the cpufreq driver. It's far more intelligent and faster switching, and of course written by intel itself for their cpus. It's also the default frequency controller if you have an intel CPU on Arch, and requires a kernel parameter to disable before you can use cpufreq, but then you are still using p_states as a backend. 
At least that is the executive summary from:
https://www.kernel.org/doc/html/v4.12/admin-guide/pm/intel_pstate.html

**Comment by connorimes** [comment]
Great, thanks for testing the changes - I tagged a new release v0.9.1 that includes the fixes.  I expect it'll make it's way into Arch whenever their package management system or package maintainers get to it.  I'm sorry that this doesn't solve your frequency scaling problems, but hopefully at least helps narrow your investigation a bit.  I won't speculate further on your problem without reading a lot more first.  I'm happy to try and answer powercap- or RAPL-related questions though.

FYI the RAPLCap rapl-configure applications only show one RAPL zone at a time (defaulting to the package zone).  To see all your powercap-related settings at a glance, including for RAPL, use `powercap-info` (the generalization of `rapl-info`) from the powercap package, which walks the Linux powercap sysfs tree.  RAPLCap's `rapl-configure-powercap` uses this backend whereas `rapl-configure-msr` uses direct MSR access, bypassing the linux powercap drivers.

For most users, I recommend relying on powercap since that offloads all the CPU-specific RAPL detection and MSR bit-level conversions to the kernel, which is really where it belongs.
